### ISSUE TITLE
plugin partly broken?

### ISSUE THREAD

**Issue by nonamenofame** [tamland/xbmc-addon-nrk#35]
Hi, I have used the plugin for some time With great success, thank you!
However, it seems like the plugin needs some updates to work again.

Searches does not Return any hits
"bla" is unable to go into a letter or numbers to drill Down and just gives an error: "script failed"
If I am accessing a folder that I earlier added to favorites, it seems like I can Access the content.

**Comment by asmundg** [comment]
#36 fixes search (and #34 fixes a separate parsing issue).

**Comment by tamland** [comment]
26f8cda8ebb587a1f1b6fe633e & c87738aca9c42eea8b
