### ISSUE TITLE
wont play episode

### ISSUE THREAD

**Issue by Aruzhu** [tamland/xbmc-addon-nrk#44]
i amrunning kodi on my raspberry pi. when i click on a episode, it just says "working" and afterwards it stops working... the working icon is gone and i am back in the same menu i was in and never left.

**Comment by bthusby** [comment]
Think I have the same problem. Running latest Kodi on RP2. When I start a video from the NRK add-on the video runs, but it isn't showing. I am able to watch it if I press the 'back' button all the way back to the home screen and one more 'back'. Then the screen is all black, and if I skip forward or backward I find the running video... Quite the work-around.
