### ISSUE TITLE
Question: Which URLs does this addon use?

### ISSUE THREAD

**Issue by olejon** [tamland/xbmc-addon-nrk#49]
This is more of a question I hope you can help me with, and if so should not take long!

Hi! I’m running NRK live using OMXPlayer on Raspbian. The problem is that after 15-30 minutes the video and audio starts to stutter. _Bandwidth is not an issue_ as restarting the omxplayer command makes it work again for x minutes again. Don’t even need to restart the VPN. Both main link and VPN server have Gigabit connections. I have tried all sorts of omxplayer command line options regarding buffering.

Looking at the source code on tv.nrk.no I’m using this URL for NRK1:

http://nrk-live-no.telenorcdn.net/21/0/hls/nrk1/playlist.m3u8?b=10-3500&bw_start=1200&no_audio_only"

They have several CDNs though as you probably know. I was hoping that changing the parameter in the URL _b=10-xxxx_ would help, but everything above 1300 makes it go full quality and everything below 1300 makes it go low. Like in the mobile apps, only two options, high or low. According to NRK’s website they have 5 qualities and downloading the m3u8 file confirms that, but I can not find a way to choose which one using the URL parameters, just high or low.

Any suggestions, **or saying, what URLs do you use?** Tried looking at your source but my Python skills are very limited although I’m a developer in several other languages.

I suspect the mobile apps use maybe use different URLs, but haven’t bothered yet to set up a middle man PC to sniff the traffic where the mobile device can connect to it’s Wi-Fi and route through Ethernet and use something like Wireshark.

Thanks!

**Comment by tamland** [comment]
Det kalles Adaptive bitrate streaming og er en del av HLS. Det er avspilleren som bestemmer hvilken versjon som spilles av. Sist jeg sjekket implementerte ikke Kodi dette og vil derfor bruker den beste basert på båndbreddeinnstillingen.

**Comment by tamland** [comment]
Fint om du kan ta spørmål i forumet

**Comment by olejon** [comment]
Takk. Bare rart man kan velge laveste (1200) eller da adaptive (> 1300). Regner med det er for mobilappene der man kan velge nettopp bare mellom de 2. Skal evt høre med NRK om det finnes en parameter for de 5 kvalitetene de faktisk har. Gir i så fall beskjed.
